### ISSUE TITLE
AttributeError: 'torch._C.Value' object has no attribute 'uniqueName'

### ISSUE THREAD

**Issue by xiaohanhaowei** [szagoruyko/pytorchviz#46]
when using torch1.3, I use `make_dot_from_trace()` function to generate the achitecture graph, it incurs an error:'AttributeError: 'torch._C.Value' object has no attribute 'uniqueName''. Any advice?

**Comment by szagoruyko** [comment]
perhaps this branch will work with 1.3? https://github.com/szagoruyko/pytorchviz/pull/37
